Repository everymeals/EveryMeal_Android, pull requests merged in 2023-10, with the labels that each got.

#61 [feature/category] 카테고리 화면 바텀시트 다이얼로그 완성
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealBottomSheetDialog.kt
  presentation/src/main/java/com/everymeal/presentation/ui/detail/DetailListContract.kt
  presentation/src/main/java/com/everymeal/presentation/ui/detail/DetailListScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/detail/DetailListViewModel.kt
  presentation/src/main/java/com/everymeal/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/theme/Color.kt
  presentation/src/main/res/drawable/icon_check_gray_mono.xml
  presentation/src/main/res/drawable/icon_check_mono.xml
  presentation/src/main/res/drawable/icon_siren_mono.xml
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik

#63 [feature/detail_restaurant] 가게 상세 뷰 구현
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealRestaurantItem.kt
  presentation/src/main/java/com/everymeal/presentation/ui/bottom/BottomNavigation.kt
  presentation/src/main/java/com/everymeal/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/main/MainScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/restaurant/DetailRestaurantContract.kt
  presentation/src/main/java/com/everymeal/presentation/ui/restaurant/DetailRestaurantScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/restaurant/DetailRestaurantViewModel.kt
  presentation/src/main/res/drawable/icon_call_mono.xml
  presentation/src/main/res/drawable/icon_camera_mono.xml
  presentation/src/main/res/drawable/icon_document_mono.xml
  presentation/src/main/res/drawable/icon_download_mono.xml
  presentation/src/main/res/drawable/icon_link_mono.xml
  presentation/src/main/res/drawable/icon_pencil_mono.xml
  presentation/src/main/res/drawable/test_image.png
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik

#65 [feature/onboarding] 온보딩 화면 구성
  app/src/main/AndroidManifest.xml
  presentation/src/main/java/com/everymeal/presentation/ui/onboarding/OnboardingActivity.kt
  presentation/src/main/java/com/everymeal/presentation/ui/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/splash/SplashActivity.kt
  presentation/src/main/java/com/everymeal/presentation/ui/whatfood/WhatFoodScreen.kt
  presentation/src/main/res/drawable/icon_onboarding_image_bowel.png
  presentation/src/main/res/drawable/icon_onboarding_image_logo.png
  presentation/src/main/res/drawable/icon_onboarding_image_school.png
  presentation/src/main/res/drawable/icon_what_food_main.png
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, ssongsik

#66 [Feature/review_star_view]: 리뷰 상세 기능
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealDialog.kt
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealGreyButton.kt
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealRedButton.kt
  presentation/src/main/java/com/everymeal/presentation/ui/review/ReviewScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/review/ReviewScreenContract.kt
  presentation/src/main/java/com/everymeal/presentation/ui/review/ReviewScreenViewModel.kt
  presentation/src/main/java/com/everymeal/presentation/ui/review/detail/ReviewDetailScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/review/write/ReviewWriteScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/theme/Color.kt
  presentation/src/main/java/com/everymeal/presentation/ui/theme/Type.kt
  presentation/src/main/res/values/strings.xml
Labels: :computer: feat, euijin

#69 [feature/onboarding-lottie] 온보딩 로티 애니메이션 추가
  presentation/src/main/assets/onboarding_food.json
  presentation/src/main/java/com/everymeal/presentation/ui/onboarding/OnboardingScreen.kt
Labels: :computer: feat, ssongsik

#74 [feature/font_add]: add font style
  presentation/src/main/java/com/everymeal/presentation/ui/theme/Type.kt
Labels: :computer: feat, euijin

#75 [feature/font_fix]: fix font style
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealBottomSheetDialog.kt
  presentation/src/main/java/com/everymeal/presentation/components/EveryMealDialog.kt
  presentation/src/main/java/com/everymeal/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/onboarding/OnboardingScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/restaurant/DetailRestaurantScreen.kt
  presentation/src/main/java/com/everymeal/presentation/ui/theme/Type.kt
  presentation/src/main/java/com/everymeal/presentation/ui/whatfood/WhatFoodScreen.kt
Labels: :wrench:fix
